# Generated by Django 5.2.6 on 2026-04-23 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentProviderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gmail_user', models.EmailField(blank=True, default='', max_length=254)),
                ('gmail_app_password', models.CharField(blank=True, default='', max_length=128)),
                ('turbosms_token', models.CharField(blank=True, default='', max_length=256)),
                ('turbosms_sender', models.CharField(blank=True, default='TurboSMS', max_length=25)),
            ],
            options={
                'verbose_name': 'Конфіг оплат/OTP',
                'verbose_name_plural': 'Конфіг оплат/OTP',
            },
        ),
    ]
