# Generated by Django 5.2.6 on 2026-04-23 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_certificateexamrequest_referralprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificatePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_eur', models.PositiveSmallIntegerField(default=25, verbose_name='Сума (€)')),
                ('reference', models.CharField(blank=True, default='', max_length=120, verbose_name='Референс/коментар')),
                ('status', models.CharField(choices=[('pending', 'Очікує'), ('success', 'Успішно'), ('failed', 'Помилка')], default='pending', max_length=10)),
                ('transaction_id', models.CharField(max_length=40, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Оплата сертифікату',
                'verbose_name_plural': 'Оплати сертифікату',
                'ordering': ['-created_at'],
            },
        ),
    ]
