# Generated by Django 5.2.13 on 2026-04-23 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_certificatepayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentproviderconfig',
            name='stripe_public_key',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='paymentproviderconfig',
            name='stripe_secret_key',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='paymentproviderconfig',
            name='stripe_webhook_secret',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
