# Generated by Django 5.2.6 on 2026-04-23 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_paymentproviderconfig_stripe_public_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentproviderconfig',
            name='stripe_public_key',
        ),
        migrations.RemoveField(
            model_name='paymentproviderconfig',
            name='stripe_secret_key',
        ),
        migrations.RemoveField(
            model_name='paymentproviderconfig',
            name='stripe_webhook_secret',
        ),
    ]
