# Generated by Django 5.2.6 on 2026-04-24 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_paymentproviderconfig_stripe_public_key_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=40, unique=True)),
                ('title', models.CharField(max_length=120)),
                ('level', models.CharField(default='A1', max_length=2)),
                ('short_pitch', models.CharField(blank=True, default='', max_length=240)),
                ('description_html', models.TextField(blank=True, default='')),
                ('required_lessons_percent', models.PositiveSmallIntegerField(default=80)),
                ('required_quiz_percent', models.PositiveSmallIntegerField(default=70)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Програма сертифікації',
                'verbose_name_plural': 'Програми сертифікації',
            },
        ),
        migrations.CreateModel(
            name='CertificateEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Активна'), ('completed', 'Завершена')], default='active', max_length=12)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='accounts.certificatepayment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_enrollments', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='accounts.certificateprogram')),
            ],
            options={
                'verbose_name': 'Запис на сертифікацію',
                'verbose_name_plural': 'Записи на сертифікацію',
                'unique_together': {('user', 'program')},
            },
        ),
        migrations.CreateModel(
            name='CertificateIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('certificate_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='issue', to='accounts.certificateenrollment')),
            ],
            options={
                'verbose_name': 'Виданий сертифікат',
                'verbose_name_plural': 'Видані сертифікати',
            },
        ),
    ]
