# Generated by Django 5.2.6 on 2026-04-24 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_certificateprogram_certificateenrollment_and_more'),
        ('learning', '0012_quizattempt_is_final_quizattempt_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateProgramLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.lesson')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_lessons', to='accounts.certificateprogram')),
            ],
            options={
                'verbose_name': 'Урок програми сертифікації',
                'verbose_name_plural': 'Уроки програм сертифікації',
                'ordering': ['order', 'id'],
                'unique_together': {('program', 'lesson')},
            },
        ),
    ]
