# Generated by Django 5.2.6 on 2026-04-24 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_certificateprogramlesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatepayment',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='accounts.certificateprogram'),
        ),
    ]
