# Generated by Django 5.2.6 on 2026-04-23 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_personalword'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500, verbose_name='Питання')),
                ('option_a', models.CharField(max_length=200, verbose_name='Варіант A')),
                ('option_b', models.CharField(max_length=200, verbose_name='Варіант B')),
                ('option_c', models.CharField(max_length=200, verbose_name='Варіант C')),
                ('correct_index', models.PositiveSmallIntegerField(help_text='0=A, 1=B, 2=C')),
                ('level', models.CharField(choices=[('A1', 'A1 — Початковий'), ('A2', 'A2 — Базовий'), ('B1', 'B1 — Середній'), ('B2', 'B2 — Вище середнього')], max_length=2, verbose_name='Рівень')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Питання тесту рівня',
                'verbose_name_plural': 'Питання тесту рівня',
                'ordering': ['level', 'order'],
            },
        ),
    ]
