# Generated by Django 5.2.6 on 2026-04-23 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0006_placementquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiumpayment',
            name='period_months',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Період (місяці)'),
        ),
    ]
