# Generated by Django 5.2.6 on 2026-04-23 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0007_premiumpayment_period_months'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='icon',
            field=models.CharField(default='', max_length=10, verbose_name='Іконка'),
        ),
    ]
