# Generated by Django 5.2.6 on 2026-04-23 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0008_alter_lesson_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiumpayment',
            name='reference',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Референс/коментар'),
        ),
    ]
