# Generated by Django 5.2.6 on 2026-04-24 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0009_premiumpayment_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='image_key',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Картинка (ключ у static, напр. weather_sun)'),
        ),
    ]
