# Generated by Django 5.2.6 on 2026-04-24 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0010_exercise_image_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='image_key',
        ),
    ]
