# Generated by Django 5.2.6 on 2026-04-24 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0011_remove_exercise_image_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='is_final',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='level',
            field=models.CharField(blank=True, choices=[('A1', 'A1 — Початковий'), ('A2', 'A2 — Базовий'), ('B1', 'B1 — Середній'), ('B2', 'B2 — Вище середнього')], default='', max_length=2),
        ),
    ]
