# Generated by Django 5.2.6 on 2026-04-24 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0012_quizattempt_is_final_quizattempt_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='course_tag',
            field=models.CharField(blank=True, db_index=True, default='', max_length=20),
        ),
    ]
