# Generated by Django 5.2.6 on 2026-04-30 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0013_lesson_course_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='daily_goal_lessons',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Ціль: уроків/день'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='daily_goal_minutes',
            field=models.PositiveSmallIntegerField(default=10, verbose_name='Ціль: хвилин/день'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='daily_goal_words',
            field=models.PositiveSmallIntegerField(default=5, verbose_name='Ціль: слів/день'),
        ),
    ]
