# Generated by Django 5.2.6 on 2026-04-30 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0014_userprofile_daily_goal_lessons_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_goal_reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Останній email-нагадувач'),
        ),
    ]
