# Generated by Django 5.2.6 on 2026-04-30 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0015_userprofile_last_goal_reminder_sent_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='last_goal_reminder_sent_at',
        ),
    ]
